# spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres
spring.datasource.url=jdbc:postgresql://db.dfjdsrazcvveurtscvah.supabase.co:5432/postgres?user=postgres&password=Huzi@1975@supabase/postgres
spring.datasource.username=postgres.dfjdsrazcvveurtscvah
spring.datasource.password=Huzi@1975@supabase/postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=none
gemini.api.key=AIzaSyCaRYJX-aL1k74-u7XXMHSjCijmZQbryI8

# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=1
# spring.datasource.hikari.leak-detection-threshold=2000  
# # Maximum time (in milliseconds) a connection can sit idle in the pool
# spring.datasource.hikari.idle-timeout=600000  
# # Maximum lifetime (in milliseconds) of a connection in the pool
# spring.datasource.hikari.max-lifetime=1800000   