spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.dfjdsrazcvveurtscvah
spring.datasource.password=Huzi@1975@supabase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
gemini.api.key=AIzaSyDoDWBI0CRzSwzNWaIHYGdM8OHidmw2uR4