spring.datasource.url={DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
gemini.api.key=${GEMINI_API_KEY}