# JPA Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# GCP config
spring.config.import=sm://
spring.cloud.gcp.secretmanager.enabled=true
spring.cloud.gcp.secretmanager.project-id=ifooty-433401

# Database Config (Local)
spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.dfjdsrazcvveurtscvah
spring.datasource.password=Huzi@1975@supabase/postgres
# Database Config (Deployment)
#spring.datasource.url=${sm://DB_URL}
#spring.datasource.username=${sm://DB_USER}
#spring.datasource.password=${sm://DB_PASS}

# API Keys
#gemini.api.key=${sm://GEMINI_API_KEY}
gemini.api.key=AIzaSyDoDWBI0CRzSwzNWaIHYGdM8OHidmw2uR4

#DB_USER=projects/ifooty-433401/secrets/DB_USER/versions/latest
#DB_PASS=projects/ifooty-433401/secrets/DB_PASS/versions/latest
#DB_NAME=projects/ifooty-433401/secrets/DB_NAME/versions/latest
#DB_URL=projects/ifooty-433401/secrets/DB_URL/versions/latest
#GEMINI_API_KEY=projects/ifooty-433401/secrets/GEMINI_API_KEY/versions/latest
